# Generated by Django 5.2.8 on 2025-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('aid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('habitat', models.CharField(max_length=50)),
            ],
        ),
    ]
